x-base_jupyter: &base_jupyter
  build:
    context: .
  image: jupyter
  ports:
    - "${PORT:-8888}:8888"
  command: >
    jupyter lab --ip=${JUPYTER_IP:-0.0.0.0} --no-browser --allow-root 
    --NotebookApp.token='${JUPYTER_TOKEN:-}' --NotebookApp.password='${JUPYTER_PASSWORD:-}' 
    --ServerApp.disable_check_xsrf=True
  volumes:
    - ./fonts:/home/jovyan/fonts
    - ./models:/home/jovyan/models
    - ./workflows:/home/jovyan/workflows

services:
  cpu:
    <<: *base_jupyter
    profiles:
      - cpu
  cuda:
    <<: *base_jupyter
    profiles:
      - cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
